language: node_js
node_js:
- 8
cache: yarn
script:
- yarn test
- yarn bundle:admin
deploy:
  matrix:
  - provider: s3
    access_key_id: AKIAJT2UYZ2H55BSA2PA
    secret_access_key:
      secure: JldbcM1kjdMFq8zVHORbO5OtaTaKl2P5u2/IycNDqnPsVJ24Li1tzOq5ThCReD7EcIi9C6INO0K1bTRAmwrZrFplwxuSJ7dg762KwxljqUU0SR7xKXU2ILZlaKhvvTzYNBuZ4OpNcxtKsWwBgvYrM+0r3GvZAuumeHmxEDHysBXsnZfd9/MaxF7jjFeP2iJkqngf+heZHB9dPTZQMckJSzj4iJfjKa/tDDL4Ksl8eo0CLivf76CgMg4a3Smwst5Regc3O7Hip+yXFmwbw+Nrg6xpn9lEb/qV/WLQxbn+TbLHLgpH/Ekv7PD60CLJZ7gM95+yPPnQ/MB33Kyh0vmpF6HlJz//h5H8/T6j1AZp3G25m3pVr9wquMm8NvDyRznmXvOg1DS3kBarMgEKns97S9xJCHi5tadKt61AHtGNXQEujiocgdI0jYDrIUXtlRlXy7ot8+topjTHw4zQy+24rEezSLTAviYnEq3oXFyg5xckzfgvOZEdI3lqZQU8QGLtjMVo6LHV82Cu2QK/5b2ts4udUCLRxEQrjGdcLCy782QDD6+v4bA/FEGhku6tpNUzBrKRVmRBsydZdcTb3F5gns9BfJogzWxXrOYxhO9Ed97lx5SJ41Qmq7PmZnaeOb8a53LLOFkH6+6pCR0n7qE7XghphFavso6uoukRsnKf8CQ=
    bucket: stage.simplecontacts.com
    skip_cleanup: true
    upload-dir: recorder-$TRAVIS_BRANCH
    local_dir: dist
    on:
      all_branches: true
  secret_access_key:
    secure: cj7W12mMgSdzBafhWScfWOz7XugMA/wUDChUrFJlbetHXDZz2wTaLekbRDVbTmxsG1VwEKOYRfhJ5v77i8CUFk/tCbehrIhs8Fq5KAxqOIbSN6opg7Skgr7VBMJMnYOCnOzeSTubQVhxyg1wHSVs0eZdpzPcu7glbY+9zeCZ+F/qsbxNgCtbge8idbr8BRyJvvcaMa/VHA3rBc2ug2EParyGrjqQhCPwPNTM+KQhXF0jryV9xZdWMLvmcrMEYpAWodP8/1Y3Uz6YUNft3AY2HsFRjwed4BvEDho0Ov2ihTvd+mKcHvlVHAbJyPVwwA8LXn/eKFxHCdWbb3SJ1rvbhnve4KgTFI8Xp7sba11kV93tqJBbvH7ZWExiSMEZ2NDDBsJc6jX1oa4vWlz3dK+rZhjjwlTUIpJ8MhRMIFwyJbxVFvKSRE9mvCjozSpQgQYBQryuzQMJU0twPwc9tiemQs7vs5h1CI1SMB4RLkA5jQr0AB4bKzUpLI8nkogOkHWSO8sb11IV47abe0jeELorY8HT53XluvYOBBiAdq3eKfx9e/iyjR3o4lz6okfphvzfuwLb5w33hbMXOhOKwgGiZg5Y0cLv38F1g4KVcfAXilStzClRAmlzmVnULuXJZMXSBthjd7kYOOKBX9Ju0/zLhgl5/PYOIxzn7PNnDCVYRz8=
