language: node_js
node_js:
  - 8
cache: yarn
script:
  - yarn test
  - yarn bundle:admin
deploy:
  - provider: s3
    access_key_id: AKIAJT2UYZ2H55BSA2PA
    secret_access_key:
      secure: cj7W12mMgSdzBafhWScfWOz7XugMA/wUDChUrFJlbetHXDZz2wTaLekbRDVbTmxsG1VwEKOYRfhJ5v77i8CUFk/tCbehrIhs8Fq5KAxqOIbSN6opg7Skgr7VBMJMnYOCnOzeSTubQVhxyg1wHSVs0eZdpzPcu7glbY+9zeCZ+F/qsbxNgCtbge8idbr8BRyJvvcaMa/VHA3rBc2ug2EParyGrjqQhCPwPNTM+KQhXF0jryV9xZdWMLvmcrMEYpAWodP8/1Y3Uz6YUNft3AY2HsFRjwed4BvEDho0Ov2ihTvd+mKcHvlVHAbJyPVwwA8LXn/eKFxHCdWbb3SJ1rvbhnve4KgTFI8Xp7sba11kV93tqJBbvH7ZWExiSMEZ2NDDBsJc6jX1oa4vWlz3dK+rZhjjwlTUIpJ8MhRMIFwyJbxVFvKSRE9mvCjozSpQgQYBQryuzQMJU0twPwc9tiemQs7vs5h1CI1SMB4RLkA5jQr0AB4bKzUpLI8nkogOkHWSO8sb11IV47abe0jeELorY8HT53XluvYOBBiAdq3eKfx9e/iyjR3o4lz6okfphvzfuwLb5w33hbMXOhOKwgGiZg5Y0cLv38F1g4KVcfAXilStzClRAmlzmVnULuXJZMXSBthjd7kYOOKBX9Ju0/zLhgl5/PYOIxzn7PNnDCVYRz8=
    bucket: stage.simplecontacts.com
    skip_cleanup: true
    upload-dir: recorder-$TRAVIS_BRANCH
    local_dir: dist
    on:
      all_branches: true
